verbose: false
instrumentation:
    default-excludes: true
    excludes: ['**/public/**', 'Gruntfile.js', 'protractor.conf.js', 'protractor-ci.conf.js', '**/spec/**']
    include-all-sources: true
reporting:
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
# For enforcing checks later on
#check:
#    global:
#        statements: 0
#        lines: 0
#        branches: 0
#        functions: 0
#        excludes: []
#    each:
#        statements: 0
#        lines: 0
#        branches: 0
#        functions: 0
#        excludes: []

